### ISSUE TITLE
[bug] [langgraph] failed to parse messages of type <class 'tuple'>

### ISSUE THREAD

**Issue by yeesian** [Arize-ai/openinference#1119]
**Describe the bug**
```
ERROR:openinference.instrumentation.langchain._tracer:Failed to get attribute.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/openinference/instrumentation/langchain/_tracer.py", line 282, in wrapper
    yield from wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openinference/instrumentation/langchain/_tracer.py", line 382, in _input_messages
    raise ValueError(f"failed to parse messages of type {type(first_messages)}")
ValueError: failed to parse messages of type <class 'tuple'>
```

**To Reproduce**

Installation:

```
!pip install -q -U \
    google-cloud-aiplatform==1.72.0 \
    langgraph==0.2.46 \
    langchain-google-vertexai==2.0.7 \
    opentelemetry-sdk \
    openinference-instrumentation-langchain==0.1.29
```

Reproducing the issue:

```python
import vertexai
from langchain_google_vertexai import ChatVertexAI
from langgraph.prebuilt import create_react_agent
from opentelemetry import trace as trace_api
from opentelemetry.sdk import trace as trace_sdk
from opentelemetry.sdk.trace.export import ConsoleSpanExporter, SimpleSpanProcessor
from openinference.instrumentation.langchain import LangChainInstrumentor

tracer_provider = trace_sdk.TracerProvider()
trace_api.set_tracer_provider(tracer_provider)
tracer_provider.add_span_processor(SimpleSpanProcessor(ConsoleSpanExporter()))

LangChainInstrumentor().instrument()
vertexai.init(project=PROJECT_ID, location=LOCATION)

def get_exchange_rate(
    currency_from: str = "USD",
    currency_to: str = "EUR",
    currency_date: str = "latest",
):
    """Retrieves the exchange rate between two currencies."""
    import requests
    response = requests.get(
        f"https://api.frankfurter.app/{currency_date}",
        params={"from": currency_from, "to": currency_to},
    )
    return response.json()

model = ChatVertexAI(model="gemini-1.5-pro")
agent = create_react_agent(
    model,
    tools=[get_exchange_rate],
)
for resp in agent.stream(
    input={"messages": [
        ("user", "What is the exchange rate from US dollars to Swedish currency?")
    ]},
    config={"configurable": {"thread_id": "thread-id"}},
):
    print(resp)
```

**Expected behavior**
No `ValueError` to be raised.

**Additional context**
You can switch to OpenAI if preferred, I just happen to have ChatVertexAI available on hand for myself to reproduce.

**Comment by RogerHYang** [comment]
Thanks for the report @yeesian. We'll be looking into this

**Comment by axiomofjoy** [comment]
Hey @yeesian, thanks for reporting this issue! We are heads down on our current milestone, but we will circle back when we free up to take a look at this. Thanks for your patience.

**Comment by RogerHYang** [comment]
We appreciate your feedback. This is fixed in openinference-instrumentation-langchain v0.1.39. Please give it a try and let us if you have any questions. Thanks!
