### ISSUE TITLE
[bug] llama-index instrumentation running in a thread causes "malformed" traces

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/openinference#306]
[6:33 PM](https://arize-ai.slack.com/archives/C05GHEKFR38/p1710981226200879)
Hey all! I'm working on using llamaindex behind a FastAPI endpoint and I've gotten OpenInference integrated and I am able to produce traces, however I am receiving this error 
```
backend-1  | [2024-03-21 00:16:45,691] [ERROR] [__init__.py:165:detach] Failed to detach context
backend-1  | Traceback (most recent call last):
backend-1  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/opentelemetry/context/__init__.py", line 163, in detach
backend-1  |     _RUNTIME_CONTEXT.detach(token)  # type: ignore
backend-1  |   File "/opt/pysetup/.venv/lib/python3.10/site-packages/opentelemetry/context/contextvars_context.py", line 50, in detach
backend-1  |     self._current_context.reset(token)  # type: ignore
backend-1  | ValueError: <Token var=<ContextVar name='current_context' default={} at 0x7fa282bc31f0> at 0x7fa269839840> was created in a different Context
```

This has led to some malformed traces and I can't quite track down the cause. This is a custom ChatEngine that that follows similar patterns to those contained in the llamaindex.core.chat_engines directory and I am worried that the threads that are started for persisting chat history are the underlying cause:
```python
     if self._memory:
                thread = Thread(
                    target=lambda x: asyncio.run(
                        chat_response.awrite_response_to_history(x)
                    ),
                    args=(self._memory,),
                )
                thread.start()
 ```

**Comment by edhenry** [comment]
Adding some more detail here. I was able to reproduce the issue by changing the `chat_mode` on the example contained in `python/examples/llama-index` directory.

Setting

```python
def get_chat_engine():
    service_context = create_service_context()
    # check if storage already exists
    if not os.path.exists(STORAGE_DIR):
        raise Exception(
            "StorageContext is empty - call 'python app/engine/generate.py' to generate the storage first"
        )
    logger = logging.getLogger("uvicorn")
    # load the existing index
    logger.info(f"Loading index from {STORAGE_DIR}...")
    storage_context = StorageContext.from_defaults(persist_dir=STORAGE_DIR)
    index = load_index_from_storage(storage_context, service_context=service_context)
    logger.info(f"Finished loading index from {STORAGE_DIR}")
    return index.as_chat_engine(chat_mode=ChatMode.CONDENSE_PLUS_CONTEXT) # Set the ChatMode here
```

This should yield the same error

```bash
Running in development mode - allowing CORS for all origins
Overriding of current TracerProvider is not allowed
Attempting to instrument while already instrumented
WARNING:  Running in development mode - allowing CORS for all origins
INFO:     Started server process [2997075]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Loading index from storage...
INFO:     Finished loading index from storage
INFO:     127.0.0.1:48352 - "POST /api/chat HTTP/1.1" 200 OK
Failed to detach context
Traceback (most recent call last):
  File "/home/tom/.cache/pypoetry/virtualenvs/app-rqL62n-7-py3.10/lib/python3.10/site-packages/opentelemetry/context/__init__.py", line 163, in detach
    _RUNTIME_CONTEXT.detach(token)  # type: ignore
  File "/home/tom/.cache/pypoetry/virtualenvs/app-rqL62n-7-py3.10/lib/python3.10/site-packages/opentelemetry/context/contextvars_context.py", line 50, in detach
    self._current_context.reset(token)  # type: ignore
ValueError: <Token var=<ContextVar name='current_context' default={} at 0x7f7dca5a3e20> at 0x7f7dcb94bac0> was created in a different Context
```

**Comment by RogerHYang** [comment]
resolved by installing openinference-instrumentation-llama-index v0.1.3
