### ISSUE TITLE
fix langchain-express js example sending traces to arize

### ISSUE THREAD

**Issue by Parker-Stafford** [Arize-ai/openinference#393]
- update commands in readme, running npm run dev on both the front end and backend directory results in connection error
- call out node version the --import flag requires node version 20
- update arize docs to make it a simple copy and paste into the instrumentation file
- add grpc install to arize docs
- Fix sending spans to arize
```
{"stack":"Error: Incorrect arguments passed\n    at ServiceClientImpl.checkOptionalUnaryResponseArguments (/Users/jackyhao/openinference/js/examples/langchain-express/backend/node_modules/@grpc/grpc-js/build/src/client.js:119:23)\n    at ServiceClientImpl.makeUnaryRequest (/Users/jackyhao/openinference/js/examples/langchain-express/backend/node_modules/@grpc/grpc-js/build/src/client.js:126:39)\n    at ServiceClientImpl.export (/Users/jackyhao/openinference/js/examples/langchain-express/backend/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)\n    at /Users/jackyhao/openinference/js/examples/langchain-express/backend/node_modules/@opentelemetry/otlp-grpc-exporter-base/build/src/grpc-exporter-transport.js:98:32\n    at new Promise (<anonymous>)\n    at GrpcExporterTransport.send (/Users/jackyhao/openinference/js/examples/langchain-express/backend/node_modules/@opentelemetry/otlp-grpc-exporter-base/build/src/grpc-exporter-transport.js:87:16)\n    at OTLPTraceExporter.send (/Users/jackyhao/openinference/js/examples/langchain-express/backend/node_modules/@opentelemetry/otlp-grpc-exporter-base/build/src/OTLPGRPCExporterNodeBase.js:88:41)\n    at /Users/jackyhao/openinference/js/examples/langchain-express/backend/node_modules/@opentelemetry/otlp-grpc-exporter-base/node_modules/@opentelemetry/otlp-exporter-base/build/src/OTLPExporterBase.js:77:22\n    at new Promise (<anonymous>)\n    at OTLPTraceExporter._export (/Users/jackyhao/openinference/js/examples/langchain-express/backend/node_modules/@opentelemetry/otlp-grpc-exporter-base/node_modules/@opentelemetry/otlp-exporter-base/build/src/OTLPExporterBase.js:74:16)","message":"Incorrect arguments passed","name":"Error"}
```

**Comment by Parker-Stafford** [comment]
closing was not able to reproduce but will update docs to make the process of adapting one of the examples for arize more clear
