### ISSUE TITLE
[bug] CrewAI instrumentation

### ISSUE THREAD

**Issue by abhijitherekar** [Arize-ai/openinference#979]
**Describe the bug**
Seeing circular dependency error while instrumenting crew-ai. 

```
    from crewai import Task
ImportError: cannot import name 'Task' from partially initialized module 'crewai' (most likely due to a circular import) (/Users/abhijit/work/tracing-ai-agents/crew-ai/crewai.py)
```

**To Reproduce**
Follow the crewai instrumentation steps

**Expected behavior**
There should be no error while instrumenting crewAI. 

**Screenshots**
```
Traceback (most recent call last):
  File "/Users/abhijit/work/tracing-ai-agents/crew-ai/crewai.py", line 16, in <module>
    CrewAIInstrumentor().instrument(tracer_provider=trace_provider)
  File "/opt/homebrew/anaconda3/envs/crew-ai-tracing/lib/python3.12/site-packages/opentelemetry/instrumentation/instrumentor.py", line 114, in instrument
    result = self._instrument(  # pylint: disable=assignment-from-no-return
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/crew-ai-tracing/lib/python3.12/site-packages/openinference/instrumentation/crewai/__init__.py", line 47, in _instrument
    self._wrap_functions()
  File "/opt/homebrew/anaconda3/envs/crew-ai-tracing/lib/python3.12/site-packages/openinference/instrumentation/crewai/__init__.py", line 80, in _wrap_functions
    wrap_execute_core()
  File "/opt/homebrew/anaconda3/envs/crew-ai-tracing/lib/python3.12/site-packages/openinference/instrumentation/crewai/__init__.py", line 51, in wrap_execute_core
    from crewai import Task
  File "/Users/abhijit/work/tracing-ai-agents/crew-ai/crewai.py", line 16, in <module>
    CrewAIInstrumentor().instrument(tracer_provider=trace_provider)
  File "/opt/homebrew/anaconda3/envs/crew-ai-tracing/lib/python3.12/site-packages/opentelemetry/instrumentation/instrumentor.py", line 114, in instrument
    result = self._instrument(  # pylint: disable=assignment-from-no-return
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/anaconda3/envs/crew-ai-tracing/lib/python3.12/site-packages/openinference/instrumentation/crewai/__init__.py", line 47, in _instrument
    self._wrap_functions()
  File "/opt/homebrew/anaconda3/envs/crew-ai-tracing/lib/python3.12/site-packages/openinference/instrumentation/crewai/__init__.py", line 80, in _wrap_functions
    wrap_execute_core()
  File "/opt/homebrew/anaconda3/envs/crew-ai-tracing/lib/python3.12/site-packages/openinference/instrumentation/crewai/__init__.py", line 51, in wrap_execute_core
    from crewai import Task
ImportError: cannot import name 'Task' from partially initialized module 'crewai' (most likely due to a circular import) (/Users/abhijit/work/tracing-ai-agents/crew-ai/crewai.py)
```

**Desktop (please complete the following information):**
 - MacOS

**Additional context**

**Comment by nate-mar** [comment]
Hi @abhijitherekar! apologies for the long delay here. I haven't been able to reproduce this. Can you confirm all the versions that are installed locally via `pip freeze` in your virtual environment and paste the output into a comment here? Thanks!

**Comment by nate-mar** [comment]
Hi there @abhijitherekar ! We're cleaning up our backlog right now, and I'm going to close this ticket for now, but please feel free to reopen it if you run into the same problem! Thanks!
